Project converted from Java to Kotlin
enzoftware/android_iptv pull request #12
Opened 2021-10-05 14:42 UTC by JudahSolomon

ChannelIem.java,ChanellList.java and Parser.java files have been converted to Kotlin

2021-10-05 17:18 UTC, enzoftware commented on app/src/main/java/com/enzoftware/androidiptv/m3u/Parser.kt
> +//            {
Remove this commented code please 🙏

2021-10-05 17:19 UTC, enzoftware commented on app/src/main/java/com/enzoftware/androidiptv/m3u/ChannelItem.kt
> +    //    }
Remove this commented code please 👍

2021-10-05 17:19 UTC, enzoftware requested changes
Please take a look on it.

2021-10-06 05:02 UTC, Rishavgupta12345 commented
ok i am working on it

2021-10-06 10:14 UTC, JudahSolomon commented
Thank you very much... i will work on it ASAP

On Wed, Oct 6, 2021 at 5:02 AM RISHAV GUPTA ***@***.***>
wrote:

> ok i am working on it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/enzoftware/android_iptv/pull/12#issuecomment-935460841>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULBWHO2IHKEDRYURBNRNNTUFPJ7DANCNFSM5FL4JGUQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-19 22:57 UTC, closed without merging